version: '3'

services:
    web:
        build: /Documents/Django/HW/django_docker
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/django_docker
        ports: 
            - "8000:8000"
        depends_on: 
            - db
            - redis
    celery_worker:
    	build: 
    	command: /start-celeryworker
    	volumes: 
    	    - .:/django_docker
    	depends_on: 
    	    - db
    	    - redis
    db:
    	image: postgres:12
    	environment:
    	    POSTGRES_USER: django_user
    	    POSTGRES_PASSWORD: Gosamu11
    	    POSTGRES_DB: postgres
    redis:
        image: redis:5
		
